# Generated by Django 3.1.7 on 2021-03-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_auto_20210327_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='rest',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='set',
            name='rest_unit',
            field=models.CharField(choices=[('sec', 'Seconds'), ('min', 'Minutes'), ('hr', 'Hours')], default='Seconds', max_length=15),
        ),
        migrations.AlterField(
            model_name='set',
            name='reps_unit',
            field=models.CharField(choices=[('RE', 'Repetitions'), ('MI', 'Minutes'), ('SE', 'Seconds'), ('KM', 'Kilometers')], default='REPETITIONS', max_length=20),
        ),
        migrations.AlterField(
            model_name='set',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
        migrations.AlterField(
            model_name='set',
            name='weight_unit',
            field=models.CharField(choices=[('KG', 'Kilograms'), ('BW', 'Body weight'), ('KH', 'Kilometers per hour')], default='KILOGRAMS', max_length=20),
        ),
    ]
