# Generated by Django 3.1.7 on 2021-03-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gym', '0003_auto_20210327_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOutPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], default='Monday', max_length=20)),
                ('aim', models.CharField(blank=True, max_length=256)),
                ('exercises', models.ManyToManyField(related_name='exercises', to='gym.ExerciseSet')),
            ],
        ),
    ]
