# Generated by Django 3.1.7 on 2021-03-29 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import training.constants


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('body', '0002_auto_20210327_1339'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('primary_muscles', models.ManyToManyField(related_name='primary_muscles', to='body.Muscle')),
                ('secondary_muscles', models.ManyToManyField(blank=True, related_name='secondary_muscles', to='body.Muscle')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.exercise')),
                ('muscles', models.ManyToManyField(related_name='muscles', to='body.Muscle')),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField(blank=True)),
                ('aim', models.CharField(blank=True, max_length=100)),
                ('exercises', models.ManyToManyField(related_name='exercises', to='training.Exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField(default=False)),
                ('reps', models.PositiveIntegerField(default=0)),
                ('reps_unit', models.CharField(choices=[('REPS', 'Repetitions'), ('MIN', 'Minutes'), ('SEC', 'Seconds'), ('KM', 'Kilometers')], default=training.constants.REPS_UNIT_CHOICES['REPS'], max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=20)),
                ('weight_unit', models.CharField(choices=[('KG', 'Kilograms'), ('BW', 'Body weight'), ('KH', 'Kilometers per hour')], default=training.constants.WEIGHT_UNIT_CHOICES['KG'], max_length=20)),
                ('rest', models.PositiveIntegerField(default=0)),
                ('rest_unit', models.CharField(choices=[('SEC', 'seconds'), ('MIN', 'Minutes'), ('HR', 'Hours')], default=training.constants.REST_UNIT_CHOICES['MIN'], max_length=20)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.exerciseset')),
            ],
        ),
        migrations.AddField(
            model_name='exerciseset',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.workout'),
        ),
    ]
