# Generated by Django 3.1.7 on 2021-03-30 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_auto_20210330_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(default=datetime.date(2021, 3, 30), verbose_name='Creation Date'),
        ),
    ]
