# Generated by Django 3.1.7 on 2021-03-30 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_auto_20210330_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='date',
        ),
        migrations.AlterField(
            model_name='workout',
            name='aim',
            field=models.CharField(max_length=100),
        ),
    ]
