# Generated by Django 3.1.7 on 2021-03-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_auto_20210330_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='aim',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='workout',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
