# Generated by Django 3.1.7 on 2021-03-30 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_auto_20210330_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='date',
            field=models.DateField(default=datetime.date(2021, 3, 30)),
        ),
    ]
