# Generated by Django 3.1.7 on 2021-03-31 09:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_workout_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseset',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise', to='training.exercise'),
        ),
        migrations.AlterField(
            model_name='exerciseset',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout', to='training.workout'),
        ),
        migrations.AlterField(
            model_name='set',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exerciseset', to='training.exerciseset'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(default=datetime.date(2021, 3, 31)),
        ),
    ]
